{"name": "Click to the func Authentication -- @1.2 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n\tGetHandleVerifier [0x00007FF739DF4C25+3179557]\n\t(No symbol) [0x00007FF739A588A0]\n\t(No symbol) [0x00007FF7398E91CA]\n\t(No symbol) [0x00007FF73993FA67]\n\t(No symbol) [0x00007FF73993FC9C]\n\t(No symbol) [0x00007FF739993627]\n\t(No symbol) [0x00007FF739967C6F]\n\t(No symbol) [0x00007FF7399902F3]\n\t(No symbol) [0x00007FF739967A03]\n\t(No symbol) [0x00007FF7399306D0]\n\t(No symbol) [0x00007FF739931983]\n\tGetHandleVerifier [0x00007FF739E567CD+3579853]\n\tGetHandleVerifier [0x00007FF739E6D1D2+3672530]\n\tGetHandleVerifier [0x00007FF739E62153+3627347]\n\tGetHandleVerifier [0x00007FF739BC092A+868650]\n\t(No symbol) [0x00007FF739A62FFF]\n\t(No symbol) [0x00007FF739A5F4A4]\n\t(No symbol) [0x00007FF739A5F646]\n\t(No symbol) [0x00007FF739A4EAA9]\n\tBaseThreadInitThunk [0x00007FFF5350E8D7+23]\n\tRtlUserThreadStart [0x00007FFF546DBF6C+44]\n\n", "trace": "  File \"C:\\Users\\trlong\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\trlong\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\herokuapp\\steps\\steps_herokuapp.py\", line 45, in step_impl\n    assert get_login_page(context).verify_subheader() == \"Welcome to the Secure Area. When you are done click logout below.\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Study\\selenium_bdd_python\\features\\herokuapp\\steps\\pages\\login_page.py\", line 49, in verify_subheader\n    return self.wait.until(EC.presence_of_element_located(self.subheader)).text # using Explicit Wait\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\trlong\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 146, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "When click func Authentication", "status": "passed", "start": 1743153775643, "stop": 1743153776138}, {"name": "And input into the username \"user2\" and password \"pass2\"", "status": "passed", "start": 1743153776138, "stop": 1743153776483}, {"name": "And enter button login", "status": "passed", "start": 1743153776483, "stop": 1743153777247}, {"name": "Then Verify user login success", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n\tGetHandleVerifier [0x00007FF739DF4C25+3179557]\n\t(No symbol) [0x00007FF739A588A0]\n\t(No symbol) [0x00007FF7398E91CA]\n\t(No symbol) [0x00007FF73993FA67]\n\t(No symbol) [0x00007FF73993FC9C]\n\t(No symbol) [0x00007FF739993627]\n\t(No symbol) [0x00007FF739967C6F]\n\t(No symbol) [0x00007FF7399902F3]\n\t(No symbol) [0x00007FF739967A03]\n\t(No symbol) [0x00007FF7399306D0]\n\t(No symbol) [0x00007FF739931983]\n\tGetHandleVerifier [0x00007FF739E567CD+3579853]\n\tGetHandleVerifier [0x00007FF739E6D1D2+3672530]\n\tGetHandleVerifier [0x00007FF739E62153+3627347]\n\tGetHandleVerifier [0x00007FF739BC092A+868650]\n\t(No symbol) [0x00007FF739A62FFF]\n\t(No symbol) [0x00007FF739A5F4A4]\n\t(No symbol) [0x00007FF739A5F646]\n\t(No symbol) [0x00007FF739A4EAA9]\n\tBaseThreadInitThunk [0x00007FFF5350E8D7+23]\n\tRtlUserThreadStart [0x00007FFF546DBF6C+44]\n\n", "trace": "  File \"C:\\Users\\trlong\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\trlong\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\herokuapp\\steps\\steps_herokuapp.py\", line 45, in step_impl\n    assert get_login_page(context).verify_subheader() == \"Welcome to the Secure Area. When you are done click logout below.\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Study\\selenium_bdd_python\\features\\herokuapp\\steps\\pages\\login_page.py\", line 49, in verify_subheader\n    return self.wait.until(EC.presence_of_element_located(self.subheader)).text # using Explicit Wait\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\trlong\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 146, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "attachments": [{"name": "Verify_user_login_success", "source": "138d7efd-d0a6-4a5b-98f7-d64cf3482c46-attachment.png", "type": "image/png"}], "start": 1743153777247, "stop": 1743153788465}], "parameters": [{"name": "username", "value": "user2"}, {"name": "password", "value": "pass2"}], "start": 1743153775293, "stop": 1743153788466, "uuid": "ecdfc161-681b-42f4-94a0-65ee4eb1adfa", "historyId": "2db698f6d7bdcd332ca13e283264a7bd", "fullName": "Example Feature: Click to the func Authentication", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Example Feature"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}